import Link from "next/link";
import { SiteHeader } from "../../components/site-header";
import { AdminAction,AdminField } from "../../components/admin-action";
import { adminWallet } from "../../lib/scout-auth";
import { database } from "../../lib/database";
export const dynamic="force-dynamic";
const eligibility=["PENDING_REVIEW","AUTHORIZED_BOUNTY","PROTOCOL_AUTHORIZED","PUBLIC_RESEARCH","OUT_OF_SCOPE"];
const states=["DRAFT","HUMAN_REVIEW","APPROVED_FOR_DISCLOSURE","DISCLOSED","ACKNOWLEDGED","BOUNTY_PENDING","BOUNTY_RECEIVED","RESOLVED"];
export default async function Admin({searchParams}:{searchParams:Promise<{eligibility?:string;status?:string}>}){
 if(!await adminWallet())return <><SiteHeader/><main className="shell py-16"><h1>PRIVATE ADMIN / ACCESS REQUIRED</h1><p>Connect and sign in with an approved admin wallet.</p></main></>;
 const filter=await searchParams;const db=database();let tq=db.from("targets").select("*").order("created_at",{ascending:false}).limit(100);if(filter.eligibility&&eligibility.includes(filter.eligibility))tq=tq.eq("eligibility",filter.eligibility);
 let iq=db.from("investigations").select("id,target_id,status,current_stage").order("created_at",{ascending:false}).limit(100);if(filter.status)iq=iq.eq("status",filter.status);
 const [targets,investigations,findings,disclosures,bounties,health]=await Promise.all([tq,iq,db.from("findings").select("id,title,severity,human_status,investigation_id").order("created_at",{ascending:false}).limit(100),db.from("disclosures").select("*").order("updated_at",{ascending:false}).limit(100),db.from("bounties").select("id,disclosure_id,investigation_id,target_id,finding_id,scout,amount_units::text,decimals,asset,status,protocol_reference,scout_units::text,buyback_units::text,distribution_tx,buyback_tx,testnet,created_at").order("created_at",{ascending:false}).limit(100),db.from("worker_health").select("updated_at").eq("id","runner").maybeSingle()]);
 if([targets,investigations,findings,disclosures,bounties,health].some(r=>r.error))return <><SiteHeader/><main className="shell py-16">Admin database unavailable. Apply the public beta migration.</main></>;
 return <><SiteHeader/><main className="shell space-y-10 py-16"><p className="eyebrow">PRIVATE / HUMAN CONTROL ROOM</p><h1 className="text-4xl">Whitehat operations.</h1><p>Worker / {health.data?`LAST HEARTBEAT ${health.data.updated_at}`:"UNAVAILABLE — queued work is retained"}</p><form className="flex flex-wrap gap-3"><select className="intake-control" name="eligibility"><option value="">ALL TARGETS</option>{eligibility.map(s=><option key={s}>{s}</option>)}</select><select name="status" className="intake-control"><option value="">ALL INVESTIGATIONS</option>{["QUEUED","RUNNING","REVIEW","COMPLETE","FAILED","INTERRUPTED"].map(s=><option key={s}>{s}</option>)}</select><button className="button button-primary">FILTER</button></form>
 <section><h2 className="eyebrow mb-5">TARGET SAFETY / ELIGIBILITY</h2>{targets.data?.map(t=><details key={t.id} className="mb-4 border border-line p-5"><summary>{t.protocol_name||t.contract_address} / {t.eligibility}</summary><p className="my-3 break-all">Chain {t.chain_id} / {t.contract_address}</p><AdminAction action="scope" id={t.id} label="SAVE SCOPE / STOP CURRENT WORK"><select name="eligibility" className="intake-control" defaultValue={t.eligibility}>{eligibility.map(s=><option key={s}>{s}</option>)}</select><AdminField name="bounty_url" label="Official bounty/security program URL" value={t.bounty_url}/><AdminField name="scope_notes" label="Scope notes" value={t.scope_notes} area/><AdminField name="allowed_contracts" label="Allowed contracts (comma separated)" value={t.allowed_contracts.join(", ")}/><AdminField name="excluded_contracts" label="Excluded contracts" value={t.excluded_contracts.join(", ")}/><AdminField name="restrictions" label="Restrictions" value={t.restrictions} area/><AdminField name="disclosure_contact" label="Private disclosure contact" value={t.disclosure_contact}/><AdminField name="admin_notes" label="Private admin notes" value={t.admin_notes} area/><label className="block text-sm"><input type="checkbox" name="local_analysis_allowed" defaultChecked={t.local_analysis_allowed}/> I reviewed the restrictions and authorize public-source local/offline analysis of the allowed target. No live tests, generated test execution or external disclosure.</label></AdminAction></details>)}</section>
 <section><h2 className="eyebrow mb-5">INVESTIGATIONS / AGENT PROGRESS</h2>{investigations.data?.map(i=><div key={i.id} className="mb-4 border border-line p-5"><Link className="text-mint" href={`/investigations/${i.id}`}>{i.id}</Link><p>{i.status} / {i.current_stage}</p><AdminAction action="queue" id={i.id} label="QUEUE WITH APPROVED SCOPE"/></div>)}</section>
 <section><h2 className="eyebrow mb-5">FINDINGS / HUMAN REVIEW QUEUE</h2>{findings.data?.map(f=><p key={f.id} className="mb-3"><Link className="text-mint underline" href={`/admin/findings/${f.id}`}>{f.title}</Link> / {f.severity} / {f.human_status??"NEEDS HUMAN REVIEW"}</p>)}</section>
 <section><h2 className="eyebrow mb-5">PRIVATE DISCLOSURES</h2>{disclosures.data?.map(d=><details key={d.id} className="mb-4 border border-line p-5"><summary>{d.id} / {d.status}</summary><pre className="my-4 max-h-96 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(d.package,null,2)}</pre><p className="my-4 text-muted">Approval records human intent only. A human must send externally; this app never sends a disclosure.</p>{states.indexOf(d.status)<states.length-1&&<AdminAction action="disclosure" id={d.id} label="RECORD NEXT HUMAN STEP"><input type="hidden" name="status" value={states[states.indexOf(d.status)+1]}/><p>Next / {states[states.indexOf(d.status)+1]}</p><AdminField name="notes" label="Human review / external delivery reference" area/></AdminAction>}{["BOUNTY_PENDING","BOUNTY_RECEIVED","RESOLVED"].includes(d.status)&&<AdminAction action="bounty" id={d.id} label="SAVE BOUNTY OUTCOME / SAME REFERENCE UPDATES"><AdminField name="amount_units" label="Amount in smallest whole units (e.g. 100000000 for 100 tokens with 6 decimals)"/><AdminField name="decimals" label="Asset decimals" value="6"/><AdminField name="asset" label="Asset name / contract"/><select name="status" className="intake-control"><option>PENDING</option><option>RECEIVED</option><option>DISTRIBUTED</option></select><AdminField name="protocol_reference" label="Protocol payment reference"/><AdminField name="distribution_tx" label="Scout distribution transaction (optional)"/><AdminField name="buyback_tx" label="Buyback transaction (optional)"/><label><input name="testnet" type="checkbox" defaultChecked/> TESTNET DEVELOPMENT DATA</label><p>Exactly 50% Scout / 50% buyback; odd smallest units go to buyback. Record only; no transaction is sent.</p></AdminAction>}</details>)}</section>
 <section><h2 className="eyebrow mb-5">BOUNTY / SCOUT / BUYBACK LINKAGE</h2>{bounties.data?.map(b=><div key={b.id} className="mb-4 border border-line p-5 text-xs"><p>{b.testnet?"TESTNET DEVELOPMENT DATA":"OPERATOR-RECORDED BOUNTY"} / {b.status} / {b.asset}</p><p className="break-all">Scout {b.scout} / {b.scout_units} units; buyback {b.buyback_units} units / decimals {b.decimals}</p><p className="break-all">Finding {b.finding_id} / disclosure {b.disclosure_id} / investigation {b.investigation_id}</p><p className="break-all">Distribution {b.distribution_tx??"PENDING"} / buyback {b.buyback_tx??"PENDING"}</p></div>)}<Link className="text-mint underline" href="/buybacks">EXISTING TESTNET DEMONSTRATION</Link></section></main></>;
}



